### ISSUE TITLE
"ValueError: No JSON object could be decoded" every time

### ISSUE THREAD

**Issue by strowger** [jdhorne/pycarwings2#12]
As of yesterday I'm getting "ValueError: No JSON object could be decoded" every time.

The app on my phone still works.

```
$ time ./get-leaf-info.py 
Prepare Session
Login...
Traceback (most recent call last):
  File "./get-leaf-info.py", line 25, in <module>
    l = s.get_leaf()
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 189, in get_leaf
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 151, in connect
    "lg": "en-US",
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 134, in _request
    j = json.loads(response.content)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

real	0m4.006s
user	0m2.928s
sys	0m0.144s
```

**Comment by jdhorne** [comment]
Yep, I'm seeing it, too. Maybe they've changed the endpoint again. I'll have to debug the protocol to see what's going on.

**Comment by strowger** [comment]
The official and unofficial phone apps still work, and haven't been updated.

They've not done something like block whatever user-agent you use have they?

**Comment by ralin3** [comment]
Leaf manager has also stopped working. 





On Wed, Feb 22, 2017, at 19:27, strowger wrote:

> The official and unofficial phone apps still work, and haven't been
> updated.
> They've not done something like block whatever user-agent you use
> have they?
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
> 


Links:

  1. https://github.com/jdhorne/pycarwings2/issues/12#issuecomment-281774915

**Comment by jdhorne** [comment]
I think they just changed the end of the service URL. I updated it to what I see from the official app, and it worked again.

I committed the change just now; give it a try.

**Comment by strowger** [comment]
Works. Thank you!

**Comment by gyathaar** [comment]
just changing the url should work fine...
guessing you got the url
https://gdcportalgw.its-mo.com/gworchest_160803A/
from the american version of the app?
interestingly the european app has a different url
https://gdcportalgw.its-mo.com/gworchest_160803EC/

guessing they have created seperate urls/servers for the different regions

**Comment by jdhorne** [comment]
@gyathaar: Just to clarify, the "A" endpoint doesn't work for you, but the "EC" version does?

**Comment by gyathaar** [comment]
No.. both endpoints work... 
(guessing the other regions may have dedicated endpoints too.. )
they all allows login from anywhere (assuming correct region is specified...)

**Comment by jdhorne** [comment]
OK, given that the endpoint works, I'm going to call this issue "closed" for now, leaving the door open for an enhancement down the road that allows one to use different endpoint URLs on a per-region basis.

Thanks for the reports, testing, feedback, and general awesomeness.

**Comment by jfarcher** [comment]
This seems to be occurring again, interestingly trying to browse to either of the above URLs returns a 404.

**Comment by strowger** [comment]
Since @jdhorne did his last fix, it's worked for me most of the time.

I've had a few hours during which API requests have failed, but most of the time it has worked.

It is working right now.

**Comment by olwalter** [comment]
For me, in Germany, it has not been working with the ...A endpoint for several days. Changing to 
BASE_URL = "https://gdcportalgw.its-mo.com/gworchest_160803EC/gdc/"
resolved the problem.

**Comment by Heiner3** [comment]
I have exactly the same problem in Germany (ValueError: No JSON object could be decoded) no matter if I use endpoint ...A or ...EC. Can somebody help? New insights?
