### ISSUE TITLE
Adding SOC to CarwingsLatestBatteryStatusResponse ok?

### ISSUE THREAD

**Issue by rduivenvoorde** [jdhorne/pycarwings2#13]
Hi, Thanks for the api! 

I have a nice graph now of my battery during driving and loading :-)

Anyway, earlier I used a php class to read out the battery status:

https://github.com/gboudreau/nissan-connect-php

And that one also returns the 'SOC' from the LatestBatteryStatus

https://github.com/gboudreau/nissan-connect-php/blob/master/NissanConnect.class.php#L177

in my experience till now this value is the exact value I see on the dashboard in the car.
While the calculated 'self.battery_percent' can be off several points:

https://github.com/jdhorne/pycarwings2/blob/master/pycarwings2/responses.py#L245

So my question / feature request, by adding one line at

https://github.com/jdhorne/pycarwings2/blob/master/pycarwings2/responses.py#L517

                self.charging_status = bs["BatteryChargingStatus"] # excisting line
                self.SOC = bs["SOC"]["Value"]  # this line added

I get myself a SOC value...

Is there a reason to NOT add it? 
Or do I interpret the value wrong?

**Comment by rduivenvoorde** [comment]
Just for fun, a graph of the SOC over 24 hours:

![selection_055](https://cloud.githubusercontent.com/assets/731673/23548631/ba3814f8-0008-11e7-960c-811c2be38385.png)

from 12:00 - 15:00 it was loading on 220V loader at home
from 16:00 you see me driving 60 km
from 22:00 you see me driving back
from 23:00 you see the leaf loading on a 3.7kW public loading place
from 8:00 you see the car driving again

I ask for the batterystatus every 15 minutes (read about good citizenship somewhere in a comment here...), but I was thinking: can you maybe reuse the session id in between the calls?
Like: on a first call you retrieve a session id, pickle it to disk, and on the next (15 min. later cron job) call you first try the pickled session id, if still working use it, else: retrieve a new session id...

I'll try to do this

**Comment by apreb** [comment]
This doesn't work for first and second generation Leaf. The best you can get is the bar count. I've added your code and the whole thing just throws a nasty exception.

**Comment by rduivenvoorde** [comment]
Ok, clean, then apparently the json is different for the different Leaf generation.
Will add an check for that node, and do a pull request...

**Comment by jdhorne** [comment]
I've committed this to master. That "if" condition should be sufficient, but, if not, we can add more!
