### ISSUE TITLE
KeyError: 'BatteryStatusRecords'

### ISSUE THREAD

**Issue by moridin1138** [jdhorne/pycarwings2#19]
@jdhorne Could something have changed on carwings/Nissan's end?

Script worked the day before, and with no changes today it does not.

`pizerow1:~/leaf $ python get-leaf-info.py
Prepare Session
Login...
get_latest_battery_status
Traceback (most recent call last):
  File "get-leaf-info.py", line 28, in <module>
    leaf_info = l.get_latest_battery_status()
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 372, in get_latest_battery_status
    return CarwingsLatestBatteryStatusResponse(response)
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/responses.py", line 508, in __init__
    CarwingsResponse.__init__(self, status["BatteryStatusRecords"])
KeyError: 'BatteryStatusRecords'
pi@pizerow1:~/leaf $`

**Comment by moridin1138** [comment]
It seems to be working again after I logged in via Leaf Manager for Android.  I had to not just refresh the app, but actually login from the settings screen.  Strange

**Comment by jdhorne** [comment]
I see odd things like this happen from time-to-time, and they eventually just go away. I don't have an explanation, other than the fact that I had to make guesses about the data structures returned by the API calls--sometimes a section of the response will drop off, whereas I assumed it would always be there. If a change seems to "stick" for a while then I'll end up modifying the code to handle it.

I'm glad you were able to get it working again.

**Comment by moridin1138** [comment]
Thanks @jdhorne 
Quick question for you.  Is there recall seeing somewhere online (maybe the node api) that GPS coordinates are returned in the JSON results from carwings/nissan.
Is there any way we can have that integrated?  Or any way I can see the raw output returned from their servers or the car to integrate it myself?

**Comment by jdhorne** [comment]
That's an odd thing--it seems like the GPS coordinates are returned for some people but not for others. I can't see them when I invoke the API, and I don't see my car's location on the official app.

Are you able to see your car's location in the official app?

**Comment by moridin1138** [comment]
@jdhorne Yes I am, it does usually work.   Though it does take a long time.

Frustrating that it's inconsistent, but it would be good to have it it's available.
