### ISSUE TITLE
"KeyError: 'cruisingRangeAcOff'" starting climate control

### ISSUE THREAD

**Issue by strowger** [jdhorne/pycarwings2#21]
I can successfully run get-leaf-info.py and see the expected output.

I used to be able to start the climate control successfully with the following script:

<pre>
$ cat start-climate.py 
#!/usr/bin/python

import pycarwings2
import time
from ConfigParser import SafeConfigParser
import logging
import sys
import pprint

logging.basicConfig(stream=sys.stdout, level=logging.ERROR)

parser = SafeConfigParser()
candidates = [ 'config.ini', 'my_config.ini' ]
found = parser.read(candidates)

username = parser.get('get-leaf-info', 'username')
password = parser.get('get-leaf-info', 'password')

logging.debug("login = %s , password = %s" % ( username , password)  )

print "Prepare Session"
s = pycarwings2.Session(username, password , "NE")
print "Login..."
l = s.get_leaf()

result_key = l.start_climate_control()
time.sleep(60)
start_cc_result = l.get_start_climate_control_result(result_key)

#result_key = l.stop_climate_control()
#time.sleep(60)
#stop_cc_result = l.get_stop_climate_control_result(result_key)
</pre>

But it now fails with the following error:

<pre>
$ ./start-climate.py
Prepare Session
Login...
Traceback (most recent call last):
  File "./start-climate.py", line 29, in <module>
    start_cc_result = l.get_start_climate_control_result(result_key)
  File "/home/strowger/.local/lib/python2.7/site-packages/pycarwings2/pycarwings2.py", line 249, in get_start_climate_control_result
    return CarwingsStartClimateControlResponse(response)
  File "/home/strowger/.local/lib/python2.7/site-packages/pycarwings2/responses.py", line 319, in __init__
    self._set_cruising_ranges(status)
  File "/home/strowger/.local/lib/python2.7/site-packages/pycarwings2/responses.py", line 50, in _set_cruising_ranges
    self.cruising_range_ac_off_km = float(status[off_key]) / 1000
KeyError: 'cruisingRangeAcOff'
</pre>

**Comment by filcole** [comment]
I've just tested this with my f[ork of the pycarwings2 library ](https://github.com/filcole/pycarwings2) and it's working fine with this **python3** code.

```
#!/usr/bin/env python

import pycarwings2
import time
from configparser import ConfigParser
import logging
import sys
import pprint

logging.basicConfig(stream=sys.stdout, level=logging.ERROR)

parser = ConfigParser()
candidates = [ 'config.ini', 'my_config.ini' ]
found = parser.read(candidates)

username = parser.get('get-leaf-info', 'username')
password = parser.get('get-leaf-info', 'password')
region = parser.get('get-leaf-info', 'region')

logging.debug("login=%s, password=%s, region=%s" % (username, password, region))

print("Prepare Session")
s = pycarwings2.Session(username, password , region)
print("Login...")
l = s.get_leaf()

result_key = l.start_climate_control()
time.sleep(60)
start_cc_result = l.get_start_climate_control_result(result_key)

#result_key = l.stop_climate_control()
#time.sleep(60)
#stop_cc_result = l.get_stop_climate_control_result(result_key)
```

**Comment by strowger** [comment]
Thank you for working on this. Sorry I no longer have a LEAF so cannot test or comment further.
