### ISSUE TITLE
AttributeError: CarwingsLatestBatteryStatusResponse instance has no attribute 'state_of_charge

### ISSUE THREAD

**Issue by glynhudson** [jdhorne/pycarwings2#24]
After merge of PR https://github.com/jdhorne/pycarwings2/pull/22  (see issue #https://github.com/jdhorne/pycarwings2/issues/13) to obtain SOC. I now get the following error when running on my 24kwh leaf. I assumed this is because my 24kwh leaf does not support SOC response? 

```
/get-leaf-info.py 
Prepare Session
Login...
get_latest_battery_status
date 01-Dec-2017 04:39
date 2017/12/01 03:40
battery_capacity2 12
battery_capacity 12
charging_status NOT_CHARGING
battery_capacity 12
battery_remaining_amount 9
charging_status NOT_CHARGING
is_charging False
is_quick_charging False
plugin_state NOT_CONNECTED
is_connected False
is_connected_to_quick_charger False
time_to_full_trickle 5:30:00
time_to_full_l2 3:00:00
time_to_full_l2_6kw 2:30:00
leaf_info.battery_percent 75.0
Traceback (most recent call last):
  File "./get-leaf-info.py", line 47, in <module>
    print "leaf_info.state_of_charge %s" % leaf_info.state_of_charge
AttributeError: CarwingsLatestBatteryStatusResponse instance has no attribute 'state_of_charge
```

**Comment by rduivenvoorde** [comment]
@glynhudson I thought I covered that by testing
`if "SOC" in bs:`  
https://github.com/jdhorne/pycarwings2/blob/master/pycarwings2/responses.py#L545
end else set it to None...

Are you sure you run both the test + module from the same version?

Or do you see a route in the code which is possible which is NOT setting the state_of_charge attribute?

With me when I do not have a SOC I get 
`leaf_info.state_of_charge None`

Happy to add an extra if here, but I would think it is just not needed....?

**Comment by glynhudson** [comment]
Yes, just double checked I'm running the latest master branch. I've just tested again and I seem to have a new error when I run `get-leaf-info.py`:

```
pi@emonpi(rw):~/pycarwings2$ git pull
Already up-to-date.
pi@emonpi(rw):~/pycarwings2$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   exemples/config.ini

no changes added to commit (use "git add" and/or "git commit -a")
pi@emonpi(rw):~/pycarwings2$ rpi-rw^C
pi@emonpi(rw):~/pycarwings2$ cd exemples/
pi@emonpi(rw):~/pycarwings2/exemples$ ls
config.ini  control_climate.py  get-leaf-info.py  get-leaf-location.py
pi@emonpi(rw):~/pycarwings2/exemples$ ./get-leaf-info.py 
Prepare Session
Login...
get_latest_battery_status
Traceback (most recent call last):
  File "./get-leaf-info.py", line 28, in <module>
    leaf_info = l.get_latest_battery_status()
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 372, in get_latest_battery_status
    return CarwingsLatestBatteryStatusResponse(response)
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/responses.py", line 542, in __init__
    self.battery_percent = 100 * float(self.battery_remaining_amount) / float(self.battery_capacity)
ZeroDivisionError: float division by zero
pi@emonpi(rw):~/pycarwings2/exemples$ ./get-leaf-location.py
Prepare Session
Login...
request_location
Traceback (most recent call last):
  File "./get-leaf-location.py", line 32, in <module>
    result_key = l.request_location()
AttributeError: Leaf instance has no attribute 'request_location'
```

**Comment by xibriz** [comment]
Did you install pycarwings2 using the pip command? If you did it's not enough to clone/pull from git. 

Try to run `pip list`
If pycarwings2 is there do a `pip uninstall pycarwings2 ` and then install.

**Comment by glynhudson** [comment]
Ah ok, sorry I forgot to re-install via pip. I just did a git pull. After a re-install I get the following error related to get location:

```
./get-leaf-location.py 
Prepare Session
Login...
request_location
ERROR:pycarwings2.pycarwings2:carwings error -5256: [MyCarFinder] API call error
Traceback (most recent call last):
  File "./get-leaf-location.py", line 32, in <module>
    result_key = l.request_location()
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 415, in request_location
    "UserId": self.session.gdc_user_id, # this userid is the 'gdc' userid
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 101, in _request_with_retry
    ret = self._request(endpoint, params)
  File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 141, in _request
    raise CarwingsError
pycarwings2.pycarwings2.CarwingsError
```

**Comment by rduivenvoorde** [comment]
@glynhudson I think you should close this issue, at it was related to the soc/state_of_charge status.

You could create a new  issue for this get-leaf-location request.
But... my guess is it is not available for your model, as earlier people showed that the get location was not available to them in the official app for 2014 model too: https://github.com/jdhorne/pycarwings2/issues/15

The get-leaf-location.py works for me (2016 model), thought it takes a looooong time at first, and the script has to login a couple of times.
Waiting for response (sleep 10)
Waiting for response (sleep 10)
Waiting for response (sleep 10)
ERROR:pycarwings2.pycarwings2:carwings error; logging in and trying request again: {u'status': 401}

**Comment by xibriz** [comment]
@rduivenvoorde the app is also painfully slow when getting location... and everything else as well.

**Comment by glynhudson** [comment]
Your totally correct, my 2014 model does not support location. I will close this issue. Thanks for your excellent support.
