### ISSUE TITLE
TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by jumpingmushroom** [jdhorne/pycarwings2#34]
Hi!

I am trying to test out the get-leaf-info.py script, by I keep getting this message. Any idea what might be causing it? Most of the info output seems fine (line VIN, mail etc.) I'm using the latest git code.

> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gdcportalgw.its-mo.com
> DEBUG:urllib3.connectionpool:https://gdcportalgw.its-mo.com:443 "POST /gworchest_160803A/gdc/BatteryStatusRecordsRequest.php HTTP/1.1" 200 None
> DEBUG:pycarwings2.pycarwings2:Response HTTP Status Code: 200
> DEBUG:pycarwings2.pycarwings2:Response HTTP Response Body: {"status":200,"BatteryStatusRecords":[]}
> Traceback (most recent call last):
>   File "./get-leaf-info.py", line 28, in <module>
>     leaf_info = l.get_latest_battery_status()
>   File "/usr/local/lib/python2.7/dist-packages/pycarwings2/pycarwings2.py", line 372, in get_latest_battery_status
>     return CarwingsLatestBatteryStatusResponse(response)
>   File "/usr/local/lib/python2.7/dist-packages/pycarwings2/responses.py", line 514, in __init__
>     bs = recs["BatteryStatus"]
> TypeError: list indices must be integers, not str

**Comment by filcole** [comment]
I've updated [get-leaf-info.py in my repo](https://github.com/filcole/pycarwings2/blob/master/examples/get-latest-battery.py).  It now checks if the server date changes as well as checking if a response is received.  Do you get the same issues here?

Please note I'm not really testing on python2, but welcome checks/fixes.

**Comment by jumpingmushroom** [comment]
@filcole Actually I started using your pycarwings2 fork and it works great now. Thanks :)
