### ISSUE TITLE
INVALID PARAMS error after nearly one year of working fine. Has the API changed?

### ISSUE THREAD

**Issue by MaxVandenbussche** [jdhorne/pycarwings2#41]
Hello,

I use pycarwings2 to do some energy-automation while charging my 2018 Leaf at my house.
Pycarwings2 has now worked for nearly a year without hiccups, refreshing the Leaf state every minute or so.

Yesterday I started getting an error message from Nissan API: {"status":404,"message":"INVALID PARAMS"}
Nothing in the script I use has been changed, also my credentials have not changed. When I entered the credentials into the Android app, the app did (eventually) update the information.

Is this happening to other people as well?

BR,
Max

**Comment by Ez2517-Git** [comment]
Yes, same issue here. NissanConnectEV 3.5.1 still works, also QuickLeaf is still working.

**Comment by MaxVandenbussche** [comment]
It seems that the pip repository is using [filcole/pycarwings2](https://github.com/filcole/pycarwings2) branch.
There a ticket has been opened and a solution has been found. I expect a PR soon.
