### ISSUE TITLE
INVALID PARAMS error

### ISSUE THREAD

**Issue by strowger** [jdhorne/pycarwings2#6]
Hi,

Thank you for writing pycarwings2. 

I've installed it on my Centos box and tried to run the example get-leaf-info.py with my username and password in the config.ini.

It fails with an "INVALID PARAMS" error:

```
$ ./get-leaf-info.py
Prepare Session
Login...
ERROR:pycarwings2.pycarwings2:carwings error INVALID PARAMS: -2010
Traceback (most recent call last):
  File "./get-leaf-info.py", line 25, in <module>
    l = s.get_leaf()
  File "/usr/lib/python2.7/site-packages/pycarwings2/pycarwings2.py", line 189, in get_leaf
    self.connect()
  File "/usr/lib/python2.7/site-packages/pycarwings2/pycarwings2.py", line 163, in connect
    "Password": encodedPassword,
  File "/usr/lib/python2.7/site-packages/pycarwings2/pycarwings2.py", line 138, in _request
    raise CarwingsError("INVALID PARAMS")
pycarwings2.pycarwings2.CarwingsError: INVALID PARAMS
```

The vehicle in question is in Europe, and it looks like your get-leaf-info.py defaults to the NE region, so I don't think it's that.

It looks from #3 like maybe this is a problem with the password encryption - do you have any hints you could offer please? I'm afraid python isn't my tool of choice and I'm a bit clueless.

Cheers

**Comment by jdhorne** [comment]
Hi, I don't know of any problems with the password encryption stuff, but I do suspect that Nissan has had some issues with their service recently, perhaps due to the cutoff of 2G service here in the USA on 12/31. I got a few errors in my setup a while back that I believe were similar, though I can't be certain that it was error number -2010.

Are you still experiencing the problem?

**Comment by frahlg** [comment]
I have the same problem. The Nissan Connect app works. 

```
Prepare Session
Login...
ERROR:pycarwings2.pycarwings2:carwings error INVALID PARAMS: -2010
Traceback (most recent call last):
  File "./get-leaf-info.py", line 25, in <module>
    l = s.get_leaf()
  File "/Library/Python/2.7/site-packages/pycarwings2/pycarwings2.py", line 189, in get_leaf
    self.connect()
  File "/Library/Python/2.7/site-packages/pycarwings2/pycarwings2.py", line 163, in connect
    "Password": encodedPassword,
  File "/Library/Python/2.7/site-packages/pycarwings2/pycarwings2.py", line 138, in _request
    raise CarwingsError("INVALID PARAMS")
pycarwings2.pycarwings2.CarwingsError: INVALID PARAMS
```

**Comment by strowger** [comment]
Hi,

Thanks for getting back to me - appreciate you taking the time to answer requests from non-paying customers :-)

Still seeing the same problem.

Phone apps (both the official Nissan one and the much-better "EVA" third party one) work fine all the time - suggests that the Nissan corporate end of things works OK.

I thought it might be some kind of CentOS/Redhat issue; I've now tried on a Debian box, and have exactly the same result.

Cheers

**Comment by strowger** [comment]
I humbly apologise.

pycarwings2 works fine. The problem was that I am a fuckwit.

I was using my email address ("carwings@domain.com") as username rather than my...username.

Changed that and it works as expected now.

**Comment by frahlg** [comment]
Thanks strowger. You are not alone, I did the exact same thing... It works now.

**Comment by jdhorne** [comment]
Haha, glad that the problem was easy to solve once you went through the excruciating process of figuring out what it was. I think @frahlg submitted a pull request that updates the example information as you suggest. I'll definitely pull that in.

Sorry again for the trouble, but I'm glad it's working for you now.

**Comment by frahlg** [comment]
Actually, after buying a new Leaf (-16) it is the email as username. On my old model (-13) it was the username and not email. Might have to do with which version of Nissan Connect.

**Comment by pdwonline** [comment]
`a new Leaf (-16) it is the email as username`
Exactly. I also have a newer leaf model and I had to use email as my login name (also for the app). Nissan app works fine, but got the invalid params error with the HA integration.  I tested using an urlencoded version (where I replaced the @ sign with `%40` but unfortunately that also has the same result. Any ideas?

**Comment by Ez2517-Git** [comment]
> 

how new is your leaf ? AFAIK pycarwings does not work any more with the latest generation (ZE1 without SD card slot for the satnav). Those models use a completely different comms protocol (and a different Nissan app).

**Comment by pdwonline** [comment]
My leaf is from 2021. Installed leaf2mqtt now and that is working fine..
